server:
  port: 8083
#spring:
#  application:
#    name: module1-service
#  profiles:
#    active: dev
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启feign对sentinel的支持

