db:
  mysql:
    host: 192.168.247.133
    port: 3306
    database: te-user
    user: root
    pw: 123456
  redis:
    host: 192.168.247.133
    port: 6379
    database: 0
    pw: 123456
#关于数据库的配置
swagger:
  title: 用户接口文档
  description: 用户接口文档
  controllers: com.microservices.user.controller
